### ISSUE TITLE
Errors running 'How to Start'

### ISSUE THREAD

**Issue by thathurtabit** [geckosio/phaser3-multiplayer-game-example#10]
Hi, this repo looks really interesting, but following the instructions [here](https://github.com/geckosio/phaser3-multiplayer-game-example#how-to-start) (on Chrome 87, Win 10).

I just get the following error after reaching `npm run start`

    :1444/.wrtc/v1/connections:1 Failed to load resource: the server responded with a status of 404 (Not Found)
    client.44ccaf22.js:204731 Unexpected token < in JSON at position 0
    (anonymous) @ client.44ccaf22.js:204731
    step @ client.44ccaf22.js:204571
    (anonymous) @ client.44ccaf22.js:204501
    rejected @ client.44ccaf22.js:204463
    client.44ccaf22.js:205394 Unexpected token < in JSON at position 0
    (anonymous) @ client.44ccaf22.js:205394
    (anonymous) @ client.44ccaf22.js:205191
    step @ client.44ccaf22.js:205024
    (anonymous) @ client.44ccaf22.js:204954
    fulfilled @ client.44ccaf22.js:204908
    :1444/favicon.ico:1

**Comment by yandeu** [comment]
What node version are you using? Have you tried node v14?

**Comment by thathurtabit** [comment]
Hi @yandeu, yep: Currently running `node v14.15.0`. I've removed my node_modules and reinstalled but no change.

**Comment by yandeu** [comment]
Looks like the newer phaser version causes this issue. I have fixed the version of phaser to 3.23. Now it works again.

**Comment by thathurtabit** [comment]
@yandeu thanks! I can confirm locking `phaser` down to `3.23.0` fixes the issue for me as well 👍
