### ISSUE TITLE
unable to run 

### ISSUE THREAD

**Issue by shohan4556** [geckosio/phaser3-multiplayer-game-example#14]
After npm installation when I try to run it to test on localserver. I got this error. 

![Code_m7sLjdgrte](https://user-images.githubusercontent.com/8347571/124305003-6309e880-db5c-11eb-91f6-f7b585141908.png)

**Comment by yandeu** [comment]
I haven't updated this example in a while. Maybe try a older node.js version?

**Comment by ErikSom** [comment]
Updating parcel to "parcel": "^2.0.0-beta.2" and removing the babel import fixed it for me (babel polyfill is deprecated: https://babeljs.io/docs/en/babel-polyfill)

**Comment by yandeu** [comment]
@ErikSom Thanks for your update. I did also just update some dependencies. Should work now :)
