### ISSUE TITLE
Please port "Phaser 3 with multiplayer physics" to geckos.io

### ISSUE THREAD

**Issue by hungpqz** [geckosio/phaser3-multiplayer-game-example#16]
As I was said that https://github.com/yandeu/phaser3-multiplayer-with-physics outdated and geckos.io is better performance, please port "Phaser 3 with multiplayer physics" to geckos.io then newbie like me can understand more about geckos.io

Thanks

**Comment by yandeu** [comment]
Geckos is hard to deploy compared to websockets.
I don't recommend geckos.io for newbies.
