### ISSUE TITLE
stuck in npm install

### ISSUE THREAD

**Issue by x1911** [geckosio/phaser3-multiplayer-game-example#9]
![image](https://user-images.githubusercontent.com/8219031/89104796-9de83580-d44e-11ea-8784-a5b264c70959.png)

macOS 10.15.5 , the install stuck....

**Comment by yandeu** [comment]
It seems to be stuck at the `wrtc` package. Please try `npm install wrtc` in a empty node project. If there is an issue with `wrtc` and your enviroment, please refer to https://github.com/node-webrtc/node-webrtc/issues

**Comment by yandeu** [comment]
What node version do you have? Have you tried node v12?

**Comment by x1911** [comment]
its v12.18.2

**Comment by x1911** [comment]
![image](https://user-images.githubusercontent.com/8219031/89112588-7d909900-d497-11ea-91a7-fe482dc5e2fb.png)
somehow the wrtc is fine

ok, now run the server, thank you for your help.

im going to try this lib instead of socket.io, to reduce the lag.

wish me luck, i really like your work, that you make this lib
thanks again
